Feature/client api
bronfood-com/backend pull request #55
Opened 2024-01-29 18:58 UTC by Solodnikov

2024-02-01 10:10 UTC, Qerced commented on src/bronfood/api/client/serializers.py
> +        return value
🖐️ Я посмотрел в исходниках, что происходит при вызове `is_valid`. Проверка организована по полям сериализатора. Берется первое поле, потом валидатор типа `validate_namefield` если есть, после валидаторы в блоке `validators` этого поля и в конце проверки всех полей уже общий `validate`. 
По этой логике у тебя `validate_phone` с сырым значением обращается к бд.

2024-02-01 10:31 UTC, Qerced commented on src/bronfood/api/client/serializers.py
> +    Сериализатор для обновления объекта клиента.
Может сюда стоит добавить create, который бы с помощью метода django "посолил" пароль перед сохранением?

2024-02-02 07:10 UTC, Solodnikov commented on src/bronfood/api/client/serializers.py
> +    Сериализатор для обновления объекта клиента.
Поясни, что значит: с помощью метода django "посолил" пароль перед сохранением?

2024-02-02 07:12 UTC, Solodnikov commented on src/bronfood/api/client/serializers.py
> +        return value
Ок, пригляжусь пристальнее тут.

2024-02-03 15:27 UTC, Qerced commented on src/bronfood/api/client/views.py
> +class CustomTokenCreateView(TokenCreateView):
Может вынести это в общий модуль view и отдельно выкатить в develop? Просто для отладки очень нужная вещь, а ждать ее со всем пр затруднит работу. Тем более он похоже одинаковый будет для клиентов и владельцев.

2024-02-03 15:33 UTC, Qerced commented on src/bronfood/api/client/views.py
> +class CustomTokenCreateView(TokenCreateView):
А кстати еще из коробки сразу нельзя его использовать? Вроде при входе достаточно token на фронт отдать.

2024-02-06 12:50 UTC, vomerf requested changes

2024-02-06 12:50 UTC, vomerf commented on src/bronfood/api/client/serializers.py
> +        return value
Вроде обычная проверка, лично я не понял что не так. @Qerced  можешь объяснить пожалуйста

2024-02-06 12:52 UTC, vomerf approved these changes

2024-02-06 12:54 UTC, vomerf commented on src/bronfood/api/client/serializers.py
> +        return value
лично я не понял что тут не так

2024-02-07 23:12 UTC, Solodnikov commented on src/bronfood/api/client/serializers.py
> +    Сериализатор для обновления объекта клиента.
засолил

2024-02-07 23:14 UTC, Solodnikov commented on src/bronfood/api/client/views.py
> +class CustomTokenCreateView(TokenCreateView):
Фронт хочет кастомный респонс с дополнительными данными, по дефолту отдает только токен.

2024-02-07 23:18 UTC, Solodnikov commented on src/bronfood/api/client/serializers.py
> +        return value
ок, то есть практичнее воткнуть в validate чтоб просто так не бегать проверяться на существание к бд без необходимости

2024-02-07 23:35 UTC, Solodnikov commented on src/bronfood/api/client/views.py
> +class CustomTokenCreateView(TokenCreateView):
Переложил в общий модуль view, там действительно место по удачнее.  Спасибо за комментарии, все вроде по делу!

2024-02-08 20:10 UTC, kmvpw reviewed
Предлагаю внести правки, чтобы flake не спотыкался.

2024-02-15 19:54 UTC, closed without merging